Missing edge case, getting error on FPL254107D4
ERROR: SpiBusEnableIOexpander: Slot-8 CPLD SPI MODE STATUS INCORRECT.  EXPECT SPI MODE ENABLED (BIT0=1).   Reg 0x22=6